### ISSUE TITLE
Create requirements.txt file

### ISSUE THREAD

**Issue by varchanaiyer** [ArunyaPaul/ntel-Unnati-Final-Submission-PS-13#2]
Generate a requirements.txt file listing all project dependencies for easy setup.

**Comment by ArunyaPaul** [comment]
Thank's for mentioning. I have tried updating the requirements.txt file to include all necessary dependencies. Please check the latest version and let me know if there are any additional dependencies required.

**Comment by ArunyaPaul** [comment]
Thanks for mentioning. I have tried updating the requirements.txt file to include all necessary dependencies. Please check the latest version and let me know if there are any additional dependencies required.
